### ISSUE TITLE
[BUG] use docker context **can not open app**

### ISSUE THREAD

**Issue by rceayo** [ropali/dockyard#29] opened 2024-10-28 06:37 UTC
**Describe the bug**

**To Reproduce**
1. use docker context **can not open app**, like `docker context create --docker host=ssh://xxx`
2. terminial use docker `docker ps -a : e73b2ccb5c34   xxxx`

**Comment by ropali** [comment] 2024-10-28 14:33
@rceayo Not sure what you are trying to say here or it looks like you are in the wrong repo. Please clearly mention what the issue is what steps to reproduce.

**Comment by rceayo** [comment] 2024-10-29 03:41
<img width="128" alt="image" src="https://github.com/user-attachments/assets/d3ed8633-c256-4e63-8a83-79d8ce53a41d">
My docker context is working normally, but the dockyard connected with docker context can't be opened, and it crashes directly, but docker using docker desktop can open dockyard normally

**Comment by rceayo** [comment] 2024-10-29 03:49
like this:
<img width="408" alt="image" src="https://github.com/user-attachments/assets/b02d2695-7bd8-4297-8abe-b108bd88a0a3">

**Comment by ropali** [comment] 2024-10-31 10:54
Ok understand, I believe you are using a Mac and this is a known issue on Macs, you need to open docker desktop (can hide the client itself in the background) so that it properly connects to docker to work. There is a existing ticket for this #8  so closing this one.

**Closed by ropali** 2024-10-31 10:54 UTC
Labels: bug
